import NextAuth from "next-auth";
import authConfig from "@/lib/auth.config";

// Built from the edge-safe config only — importing lib/auth.ts here would
// pull the Prisma pg adapter and bcryptjs into the Edge middleware bundle,
// neither of which run there. Redirect-to-/login on failure is handled by
// authConfig's `authorized` callback (Auth.js's own middleware convention).
export const { auth: middleware } = NextAuth(authConfig);

export const config = {
  // robots.txt is generated by app/robots.ts and must stay reachable without a
  // session — otherwise the middleware redirects the crawler to /login and the
  // file might as well not exist. Same for the icons: a redirect there shows
  // up as a broken tab icon rather than as an auth problem.
  matcher: [
    "/((?!api|_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|icon.png|apple-icon.png|opengraph-image).*)",
  ],
};
